info:
  app:
    name: geotag-service
    description: Manages the geolocation of items

server:
  port: 8024

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

microservice:
  nbsokContentUrl: http://www.nb.no/nbsok/nb/{sesamid}
  fotoContentUrl: http://www.nb.no/foto/nb/{sesamid}