info:
  app:
    name: geotag-service
    description: Manages the geolocation of items

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

microservice:
  nbsokContentUrl: http://www.nb.no/nbsok/nb/{sesamid}
  fotoContentUrl: http://www.nb.no/foto/nb/{sesamid}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/